### ISSUE TITLE
Design von der Schule

### ISSUE THREAD

**Issue by Thiritin** [IT9x-alpha/laufometer-frontend#1]
Wir benötigen von der Schule die Brand Guidelines bzw. Coperate Identity.

- Logo als SVG
- Hauptfarben Rot, Grün und Blau als HEX Codes.
- Grautones des Hintergrund und ggf. Grafiken von der Website

**Comment by hedayati-m** [comment]
**Hauptfarben**: 
- Rot: #e4032e
- Blau: #004f9f
- Grün: #00983a

**Grautones**
- Hell : #a4cedf
- Dunkel: #454545

**Fonts**
- Header
  -H1
font-family: "ExoReg", sans-serif
font-size:

**Comment by Malucatos** [comment]
Logo der Schule 
[Schullogo ITECH BS14 ](https://cdn.discordapp.com/attachments/773145086153850891/773905057887420456/logo-hor.svg)

**Comment by Thiritin** [comment]
LGTM
