### ISSUE TITLE
Klassenranking

### ISSUE THREAD

**Issue by Thiritin** [IT9x-alpha/laufometer-frontend#2]
Am besten irgendwie sowas wie eine Grafik oder Tabelle. Ob es ggf. nach Farbe o.ä. gelistet ist steht noch zur diskussion.

**Comment by Malucatos** [comment]
Zur Aufbereitung bzw. Darstellung der Ranking könnte man verschiedene Visuelle Darstellungen nutzen.
Dafür könnte man evtl. sich von diesem Javascript Charts etwas zu nutzen machen (Kompatibilität/Integration)

https://www.chartjs.org/samples/latest/

**Comment by Malucatos** [comment]
https://www.digitalocean.com/community/tutorials/vuejs-vue-chart-js für Vue.js
