### ISSUE TITLE
Grafische Aufbereitung der Kilometer (Ranking)| Vorschlag

### ISSUE THREAD

**Issue by Malucatos** [IT9x-alpha/laufometer-frontend#4]
Zur Aufbereitung bzw. Darstellung der Ranking könnte man verschiedene Visuelle Darstellungen nutzen.
Dafür könnte man evtl. sich von diesem Javascript Charts etwas zu nutzen machen (Kompatibilität/Integration)

https://www.chartjs.org/samples/latest/

**Comment by Thiritin** [comment]
duplicate of #2
